language: go
os:
  - linux
go:
  - 1.8
services: mongodb
before_script:
  - "sudo apt-get install zookeeperd"
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - go build ./...
  - go fmt ./...
  - go vet ./...
  - go test -i -race ./...
  - go test -race -covermode atomic -coverprofile=profile.cov
  - goveralls -coverprofile=profile.cov -service=travis-ci